name: PR CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    env:
      TAMAGO_VERSION: 1.20.6
      TAMAGO: /usr/local/tamago-go/bin/go
      APPLET_PRIVATE_KEY: /tmp/applet.sec
      APPLET_PUBLIC_KEY: /tmp/applet.pub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - name: Install tools
      run: |
        wget -q https://github.com/usbarmory/tamago-go/releases/download/tamago-go${TAMAGO_VERSION}/tamago-go${TAMAGO_VERSION}.linux-amd64.tar.gz
        sudo tar -xf tamago-go${TAMAGO_VERSION}.linux-amd64.tar.gz -C /
        sudo apt install protobuf-compiler protoc-gen-go signify-openbsd
    - name: Create throwaway keys
      run: |
        go run github.com/transparency-dev/serverless-log/cmd/generate_keys@HEAD --key_name="DEV-APPLET" --out_priv=${APPLET_PRIVATE_KEY} --out_pub=${APPLET_PUBLIC_KEY}
    - name: Make
      run: |
        DEBUG=1 make trusted_applet
